newspaper:
  title: "The Dario Times"
  language: "it"
  max_articles_per_feed: 2
  send_to_kindle: true
  include_images: true

feeds:
  - name: "Mia mamma usa Linux"
    url: "https://www.miamammausalinux.org/feed/"
    category: "OS"
  - name: "Marco's Box"
    url: "https://www.marcosbox.com/feed/"
    category: "OS"
  - name: "Red Hot Cyber"
    url: "https://www.redhotcyber.com/feed/"
    category: "Cyber Security"
  - name: "Gamesource"
    url: "https://www.gamesource.it/feed/gn"
    category: "Videogames"